version: '3.8'

services:
  rabbitmq:
    image: pivotalrabbitmq/rabbitmq-delayed-message-exchange
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
