services:

  customer:
    restart: unless-stopped
    build:
      context: .
      args:
        SERVICE: CustomerService
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__MongoDb: ${MONGODB_URI}
      RabbitMq__Uri: ${RABBITMQ_URI}

  booking:
    restart: unless-stopped
    build:
      context: .
      args:
        SERVICE: BookingService
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__MongoDb: ${MONGODB_URI}
      RabbitMq__Uri: ${RABBITMQ_URI}

  fare:
    restart: unless-stopped
    build:
      context: .
      args:
        SERVICE: FareEstimationService
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RapidApi__Key: ${RAPIDAPI_KEY}
      OpenCage__Key: ${OPENCAGE_KEY}

  location:
    restart: unless-stopped
    build:
      context: .
      args:
        SERVICE: LocationService
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__MongoDb: ${MONGODB_URI}
      RapidApi__Key: ${RAPIDAPI_KEY}
      OpenCage__Key: ${OPENCAGE_KEY}

  payment:
    restart: unless-stopped
    build:
      context: .
      args:
        SERVICE: PaymentService
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__MongoDb: ${MONGODB_URI}
      Services__GatewayApi__BaseUrl: http://gateway:8080/api/gateway/

  gateway:
    restart: unless-stopped
    build:
      context: .
      args:
        SERVICE: GatewayAPI
    ports:
      - "7000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Services__Customer: http://customer:8080
      Services__Booking: http://booking:8080
      Services__Payment: http://payment:8080
      Services__Location: http://location:8080
      Services__FareEstimation: http://fare:8080
      Cors__AllowedOrigin: ${PUBLIC_FRONTEND_URL}

  frontend:
    restart: unless-stopped
    build:
      context: .
      args:
        SERVICE: WebFrontend
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      GatewayService__BaseUrl: http://gateway:8080/api/gateway
      GatewayService__PublicBaseUrl: ${PUBLIC_GATEWAY_URL}